const FIFA_COLORS = [
  "#e30000",
  "#6c00f4",
  "#3150f4",
  "#005845",
  "#ff3d12",
  "#a47cf4",
  "#06ca4f",
  "#a4ed00",
  "#ff9a82",
  "#e81768",
  "#59edcc",
  "#eaff2f",
];

const DATA_SOURCES = {
  groups: {
    label: "Grupos",
    name: "FIFA World Cup 2026 / Opta Analyst",
    url: "https://theanalyst.com/articles/fifa-world-cup-2026-groups-predictions-previews",
  },
  probability: {
    label: "Probabilidad",
    name: "Opta Analyst Supercomputer, junio 2026",
    url: "https://theanalyst.com/articles/who-will-win-2026-fifa-world-cup-predictions-opta-supercomputer",
  },
  history: {
    label: "Historial",
    name: "Historial mundialista FIFA/Wikipedia",
    url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/teams",
  },
};

const GROUPS = {
  A: ["mexico", "south-africa", "korea", "czech-republic"],
  B: ["canada", "bosnia", "qatar", "switzerland"],
  C: ["brazil", "morocco", "haiti", "scotland"],
  D: ["usa", "paraguay", "australia", "turkey"],
  E: ["germany", "curacao", "cote-divoire", "ecuador"],
  F: ["netherlands", "japan", "sweden", "tunisia"],
  G: ["belgium", "egypt", "iran", "new-zealand"],
  H: ["spain", "cabo-verde", "saudi-arabia", "uruguay"],
  I: ["france", "senegal", "iraq", "norway"],
  J: ["argentina", "algeria", "austria", "jordan"],
  K: ["portugal", "dr-congo", "uzbekistan", "colombia"],
  L: ["england", "croatia", "ghana", "panama"],
};

const POTS = [
  {
    id: 1,
    name: "Bote 1",
    countries: [
      "canada",
      "mexico",
      "usa",
      "spain",
      "argentina",
      "france",
      "england",
      "brazil",
      "portugal",
      "netherlands",
      "belgium",
      "germany",
    ],
  },
  {
    id: 2,
    name: "Bote 2",
    countries: [
      "croatia",
      "morocco",
      "colombia",
      "uruguay",
      "switzerland",
      "japan",
      "senegal",
      "iran",
      "korea",
      "ecuador",
      "austria",
      "australia",
    ],
  },
  {
    id: 3,
    name: "Bote 3",
    countries: [
      "norway",
      "panama",
      "egypt",
      "algeria",
      "scotland",
      "paraguay",
      "tunisia",
      "cote-divoire",
      "uzbekistan",
      "qatar",
      "saudi-arabia",
      "south-africa",
    ],
  },
  {
    id: 4,
    name: "Bote 4",
    countries: [
      "jordan",
      "cabo-verde",
      "ghana",
      "curacao",
      "haiti",
      "new-zealand",
      "bosnia",
      "sweden",
      "turkey",
      "czech-republic",
      "dr-congo",
      "iraq",
    ],
  },
];

const COUNTRY_DATA = {
  canada: {
    id: "canada",
    name: "Canadá",
    shortName: "CAN",
    flagCode: "ca",
    color: "#e30000",
    group: "B",
    bestParticipation: "Fase de grupos",
    probability: 0.12,
    players: [
      ["Alphonso Davies", "Lateral izquierdo"],
      ["Jonathan David", "Delantero"],
      ["Stephen Eustáquio", "Mediocampista"],
    ],
  },
  mexico: {
    id: "mexico",
    name: "México",
    shortName: "MEX",
    flagCode: "mx",
    color: "#005845",
    group: "A",
    bestParticipation: "Cuartos de final, 1970 y 1986",
    probability: 0.8,
    players: [
      ["Edson Álvarez", "Mediocentro"],
      ["Santiago Giménez", "Delantero"],
      ["Johan Vásquez", "Defensa central"],
    ],
  },
  usa: {
    id: "usa",
    name: "Estados Unidos",
    shortName: "USA",
    flagCode: "us",
    color: "#3150f4",
    group: "D",
    bestParticipation: "Tercer lugar, 1930",
    probability: 1.2,
    players: [
      ["Christian Pulisic", "Extremo"],
      ["Weston McKennie", "Mediocampista"],
      ["Tyler Adams", "Mediocentro"],
    ],
  },
  spain: {
    id: "spain",
    name: "España",
    shortName: "ESP",
    flagCode: "es",
    color: "#e30000",
    group: "H",
    bestParticipation: "Campeón, 2010",
    probability: 16.1,
    players: [
      ["Lamine Yamal", "Extremo"],
      ["Rodri", "Mediocentro"],
      ["Pedri", "Mediocampista"],
    ],
  },
  argentina: {
    id: "argentina",
    name: "Argentina",
    shortName: "ARG",
    flagCode: "ar",
    color: "#59aee8",
    group: "J",
    bestParticipation: "Campeón, 1978, 1986 y 2022",
    probability: 10.4,
    players: [
      ["Lionel Messi", "Delantero"],
      ["Lautaro Martínez", "Delantero"],
      ["Emiliano Martínez", "Portero"],
    ],
  },
  france: {
    id: "france",
    name: "Francia",
    shortName: "FRA",
    flagCode: "fr",
    color: "#3150f4",
    group: "I",
    bestParticipation: "Campeón, 1998 y 2018",
    probability: 13,
    players: [
      ["Kylian Mbappé", "Delantero"],
      ["Ousmane Dembélé", "Extremo"],
      ["William Saliba", "Defensa central"],
    ],
  },
  england: {
    id: "england",
    name: "Inglaterra",
    shortName: "ENG",
    flagCode: "gb-eng",
    color: "#ffffff",
    group: "L",
    bestParticipation: "Campeón, 1966",
    probability: 11.2,
    players: [
      ["Harry Kane", "Delantero"],
      ["Jude Bellingham", "Mediocampista"],
      ["Bukayo Saka", "Extremo"],
    ],
  },
  brazil: {
    id: "brazil",
    name: "Brasil",
    shortName: "BRA",
    flagCode: "br",
    color: "#06ca4f",
    group: "C",
    bestParticipation: "Campeón, 1958, 1962, 1970, 1994 y 2002",
    probability: 6.6,
    players: [
      ["Vinícius Júnior", "Extremo"],
      ["Raphinha", "Extremo"],
      ["Marquinhos", "Defensa central"],
    ],
  },
  portugal: {
    id: "portugal",
    name: "Portugal",
    shortName: "POR",
    flagCode: "pt",
    color: "#e30000",
    group: "K",
    bestParticipation: "Tercer lugar, 1966",
    probability: 7,
    players: [
      ["Cristiano Ronaldo", "Delantero"],
      ["Bruno Fernandes", "Mediocampista"],
      ["Vitinha", "Mediocampista"],
    ],
  },
  netherlands: {
    id: "netherlands",
    name: "Países Bajos",
    shortName: "NED",
    flagCode: "nl",
    color: "#ff6f00",
    group: "F",
    bestParticipation: "Subcampeón, 1974, 1978 y 2010",
    probability: 3.6,
    players: [
      ["Virgil van Dijk", "Defensa central"],
      ["Frenkie de Jong", "Mediocampista"],
      ["Xavi Simons", "Mediapunta"],
    ],
  },
  belgium: {
    id: "belgium",
    name: "Bélgica",
    shortName: "BEL",
    flagCode: "be",
    color: "#e30000",
    group: "G",
    bestParticipation: "Tercer lugar, 2018",
    probability: 2.4,
    players: [
      ["Kevin De Bruyne", "Mediocampista"],
      ["Jérémy Doku", "Extremo"],
      ["Thibaut Courtois", "Portero"],
    ],
  },
  germany: {
    id: "germany",
    name: "Alemania",
    shortName: "GER",
    flagCode: "de",
    color: "#111111",
    group: "E",
    bestParticipation: "Campeón, 1954, 1974, 1990 y 2014",
    probability: 5.1,
    players: [
      ["Jamal Musiala", "Mediapunta"],
      ["Florian Wirtz", "Mediapunta"],
      ["Joshua Kimmich", "Mediocampista"],
    ],
  },
  croatia: {
    id: "croatia",
    name: "Croacia",
    shortName: "CRO",
    flagCode: "hr",
    color: "#e30000",
    group: "L",
    bestParticipation: "Subcampeón, 2018",
    probability: 1.6,
    players: [
      ["Luka Modrić", "Mediocampista"],
      ["Joško Gvardiol", "Defensa"],
      ["Mateo Kovačić", "Mediocampista"],
    ],
  },
  morocco: {
    id: "morocco",
    name: "Marruecos",
    shortName: "MAR",
    flagCode: "ma",
    color: "#e30000",
    group: "C",
    bestParticipation: "Semifinales, 2022",
    probability: 1.9,
    players: [
      ["Achraf Hakimi", "Lateral derecho"],
      ["Yassine Bounou", "Portero"],
      ["Sofyan Amrabat", "Mediocentro"],
    ],
  },
  colombia: {
    id: "colombia",
    name: "Colombia",
    shortName: "COL",
    flagCode: "co",
    color: "#f7d117",
    group: "K",
    bestParticipation: "Cuartos de final, 2014",
    probability: 2.1,
    players: [
      ["Luis Díaz", "Extremo"],
      ["James Rodríguez", "Mediapunta"],
      ["Jhon Durán", "Delantero"],
    ],
  },
  uruguay: {
    id: "uruguay",
    name: "Uruguay",
    shortName: "URU",
    flagCode: "uy",
    color: "#59aee8",
    group: "H",
    bestParticipation: "Campeón, 1930 y 1950",
    probability: 1.1,
    players: [
      ["Federico Valverde", "Mediocampista"],
      ["Darwin Núñez", "Delantero"],
      ["Ronald Araújo", "Defensa central"],
    ],
  },
  switzerland: {
    id: "switzerland",
    name: "Suiza",
    shortName: "SUI",
    flagCode: "ch",
    color: "#e30000",
    group: "B",
    bestParticipation: "Cuartos de final, 1934, 1938 y 1954",
    probability: 1,
    players: [
      ["Granit Xhaka", "Mediocampista"],
      ["Manuel Akanji", "Defensa central"],
      ["Gregor Kobel", "Portero"],
    ],
  },
  japan: {
    id: "japan",
    name: "Japón",
    shortName: "JPN",
    flagCode: "jp",
    color: "#ffffff",
    group: "F",
    bestParticipation: "Octavos de final",
    probability: 0.9,
    players: [
      ["Kaoru Mitoma", "Extremo"],
      ["Takefusa Kubo", "Mediapunta"],
      ["Wataru Endo", "Mediocentro"],
    ],
  },
  senegal: {
    id: "senegal",
    name: "Senegal",
    shortName: "SEN",
    flagCode: "sn",
    color: "#06ca4f",
    group: "I",
    bestParticipation: "Cuartos de final, 2002",
    probability: 0.7,
    players: [
      ["Sadio Mané", "Delantero"],
      ["Kalidou Koulibaly", "Defensa central"],
      ["Pape Matar Sarr", "Mediocampista"],
    ],
  },
  iran: {
    id: "iran",
    name: "Irán",
    shortName: "IRN",
    flagCode: "ir",
    color: "#06ca4f",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.16,
    players: [
      ["Mehdi Taremi", "Delantero"],
      ["Sardar Azmoun", "Delantero"],
      ["Alireza Jahanbakhsh", "Extremo"],
    ],
  },
  korea: {
    id: "korea",
    name: "Corea del Sur",
    shortName: "KOR",
    flagCode: "kr",
    color: "#3150f4",
    group: "A",
    bestParticipation: "Cuarto lugar, 2002",
    probability: 0.22,
    players: [
      ["Son Heung-min", "Delantero"],
      ["Kim Min-jae", "Defensa central"],
      ["Lee Kang-in", "Mediapunta"],
    ],
  },
  ecuador: {
    id: "ecuador",
    name: "Ecuador",
    shortName: "ECU",
    flagCode: "ec",
    color: "#f7d117",
    group: "E",
    bestParticipation: "Octavos de final, 2006",
    probability: 1.4,
    players: [
      ["Moisés Caicedo", "Mediocampista"],
      ["Piero Hincapié", "Defensa central"],
      ["Pervis Estupiñán", "Lateral izquierdo"],
    ],
  },
  austria: {
    id: "austria",
    name: "Austria",
    shortName: "AUT",
    flagCode: "at",
    color: "#e30000",
    group: "J",
    bestParticipation: "Tercer lugar, 1954",
    probability: 0.6,
    players: [
      ["David Alaba", "Defensa"],
      ["Marcel Sabitzer", "Mediocampista"],
      ["Konrad Laimer", "Mediocampista"],
    ],
  },
  australia: {
    id: "australia",
    name: "Australia",
    shortName: "AUS",
    flagCode: "au",
    color: "#f7d117",
    group: "D",
    bestParticipation: "Octavos de final, 2006 y 2022",
    probability: 0.28,
    players: [
      ["Mathew Ryan", "Portero"],
      ["Jackson Irvine", "Mediocampista"],
      ["Harry Souttar", "Defensa central"],
    ],
  },
  norway: {
    id: "norway",
    name: "Noruega",
    shortName: "NOR",
    flagCode: "no",
    color: "#e30000",
    group: "I",
    bestParticipation: "Octavos de final, 1998",
    probability: 3.5,
    players: [
      ["Erling Haaland", "Delantero"],
      ["Martin Ødegaard", "Mediocampista"],
      ["Alexander Sørloth", "Delantero"],
    ],
  },
  panama: {
    id: "panama",
    name: "Panamá",
    shortName: "PAN",
    flagCode: "pa",
    color: "#e30000",
    group: "L",
    bestParticipation: "Fase de grupos, 2018",
    probability: 0.07,
    players: [
      ["Michael Murillo", "Lateral derecho"],
      ["Adalberto Carrasquilla", "Mediocampista"],
      ["José Fajardo", "Delantero"],
    ],
  },
  egypt: {
    id: "egypt",
    name: "Egipto",
    shortName: "EGY",
    flagCode: "eg",
    color: "#e30000",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.18,
    players: [
      ["Mohamed Salah", "Extremo"],
      ["Omar Marmoush", "Delantero"],
      ["Trézéguet", "Extremo"],
    ],
  },
  algeria: {
    id: "algeria",
    name: "Argelia",
    shortName: "ALG",
    flagCode: "dz",
    color: "#06ca4f",
    group: "J",
    bestParticipation: "Octavos de final, 2014",
    probability: 0.2,
    players: [
      ["Riyad Mahrez", "Extremo"],
      ["Ismaël Bennacer", "Mediocampista"],
      ["Ramy Bensebaini", "Defensa"],
    ],
  },
  scotland: {
    id: "scotland",
    name: "Escocia",
    shortName: "SCO",
    flagCode: "gb-sct",
    color: "#3150f4",
    group: "C",
    bestParticipation: "Fase de grupos",
    probability: 0.2,
    players: [
      ["Andy Robertson", "Lateral izquierdo"],
      ["Scott McTominay", "Mediocampista"],
      ["John McGinn", "Mediocampista"],
    ],
  },
  paraguay: {
    id: "paraguay",
    name: "Paraguay",
    shortName: "PAR",
    flagCode: "py",
    color: "#e30000",
    group: "D",
    bestParticipation: "Cuartos de final, 2010",
    probability: 0.35,
    players: [
      ["Miguel Almirón", "Mediapunta"],
      ["Julio Enciso", "Delantero"],
      ["Diego Gómez", "Mediocampista"],
    ],
  },
  tunisia: {
    id: "tunisia",
    name: "Túnez",
    shortName: "TUN",
    flagCode: "tn",
    color: "#e30000",
    group: "F",
    bestParticipation: "Fase de grupos",
    probability: 0.09,
    players: [
      ["Ellyes Skhiri", "Mediocampista"],
      ["Hannibal Mejbri", "Mediocampista"],
      ["Ali Abdi", "Lateral izquierdo"],
    ],
  },
  "cote-divoire": {
    id: "cote-divoire",
    name: "Costa de Marfil",
    shortName: "CIV",
    flagCode: "ci",
    color: "#ff7a00",
    group: "E",
    bestParticipation: "Fase de grupos",
    probability: 0.4,
    players: [
      ["Franck Kessié", "Mediocampista"],
      ["Simon Adingra", "Extremo"],
      ["Evan Ndicka", "Defensa central"],
    ],
  },
  uzbekistan: {
    id: "uzbekistan",
    name: "Uzbekistán",
    shortName: "UZB",
    flagCode: "uz",
    color: "#59edcc",
    group: "K",
    bestParticipation: "Debut mundialista",
    probability: 0.04,
    players: [
      ["Eldor Shomurodov", "Delantero"],
      ["Abbosbek Fayzullaev", "Mediapunta"],
      ["Abdukodir Khusanov", "Defensa central"],
    ],
  },
  qatar: {
    id: "qatar",
    name: "Catar",
    shortName: "QAT",
    flagCode: "qa",
    color: "#850d0d",
    group: "B",
    bestParticipation: "Fase de grupos, 2022",
    probability: 0.08,
    players: [
      ["Akram Afif", "Extremo"],
      ["Almoez Ali", "Delantero"],
      ["Boualem Khoukhi", "Defensa"],
    ],
  },
  "saudi-arabia": {
    id: "saudi-arabia",
    name: "Arabia Saudita",
    shortName: "KSA",
    flagCode: "sa",
    color: "#005845",
    group: "H",
    bestParticipation: "Octavos de final, 1994",
    probability: 0.11,
    players: [
      ["Salem Al-Dawsari", "Extremo"],
      ["Saud Abdulhamid", "Lateral derecho"],
      ["Firas Al-Buraikan", "Delantero"],
    ],
  },
  "south-africa": {
    id: "south-africa",
    name: "Sudáfrica",
    shortName: "RSA",
    flagCode: "za",
    color: "#06ca4f",
    group: "A",
    bestParticipation: "Fase de grupos",
    probability: 0.1,
    players: [
      ["Ronwen Williams", "Portero"],
      ["Teboho Mokoena", "Mediocampista"],
      ["Percy Tau", "Delantero"],
    ],
  },
  jordan: {
    id: "jordan",
    name: "Jordania",
    shortName: "JOR",
    flagCode: "jo",
    color: "#e30000",
    group: "J",
    bestParticipation: "Debut mundialista",
    probability: 0.02,
    players: [
      ["Musa Al-Taamari", "Extremo"],
      ["Yazan Al-Naimat", "Delantero"],
      ["Noor Al-Rawabdeh", "Mediocampista"],
    ],
  },
  "cabo-verde": {
    id: "cabo-verde",
    name: "Cabo Verde",
    shortName: "CPV",
    flagCode: "cv",
    color: "#3150f4",
    group: "H",
    bestParticipation: "Debut mundialista",
    probability: 0.02,
    players: [
      ["Ryan Mendes", "Extremo"],
      ["Garry Rodrigues", "Extremo"],
      ["Logan Costa", "Defensa central"],
    ],
  },
  ghana: {
    id: "ghana",
    name: "Ghana",
    shortName: "GHA",
    flagCode: "gh",
    color: "#f7d117",
    group: "L",
    bestParticipation: "Cuartos de final, 2010",
    probability: 0.25,
    players: [
      ["Mohammed Kudus", "Mediapunta"],
      ["Thomas Partey", "Mediocampista"],
      ["Antoine Semenyo", "Delantero"],
    ],
  },
  curacao: {
    id: "curacao",
    name: "Curazao",
    shortName: "CUW",
    flagCode: "cw",
    color: "#3150f4",
    group: "E",
    bestParticipation: "Debut mundialista",
    probability: 0.005,
    players: [
      ["Juninho Bacuna", "Mediocampista"],
      ["Eloy Room", "Portero"],
      ["Juriën Gaari", "Defensa"],
    ],
  },
  haiti: {
    id: "haiti",
    name: "Haití",
    shortName: "HAI",
    flagCode: "ht",
    color: "#3150f4",
    group: "C",
    bestParticipation: "Fase de grupos, 1974",
    probability: 0.01,
    players: [
      ["Duckens Nazon", "Delantero"],
      ["Frantzdy Pierrot", "Delantero"],
      ["Jean-Ricner Bellegarde", "Mediocampista"],
    ],
  },
  "new-zealand": {
    id: "new-zealand",
    name: "Nueva Zelanda",
    shortName: "NZL",
    flagCode: "nz",
    color: "#111111",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.05,
    players: [
      ["Chris Wood", "Delantero"],
      ["Sarpreet Singh", "Mediocampista"],
      ["Liberato Cacace", "Lateral izquierdo"],
    ],
  },
  bosnia: {
    id: "bosnia",
    name: "Bosnia y Herzegovina",
    shortName: "BIH",
    flagCode: "ba",
    color: "#3150f4",
    group: "B",
    bestParticipation: "Fase de grupos, 2014",
    probability: 0.06,
    players: [
      ["Edin Džeko", "Delantero"],
      ["Sead Kolašinac", "Defensa"],
      ["Amar Dedić", "Lateral derecho"],
    ],
  },
  sweden: {
    id: "sweden",
    name: "Suecia",
    shortName: "SWE",
    flagCode: "se",
    color: "#f7d117",
    group: "F",
    bestParticipation: "Subcampeón, 1958",
    probability: 0.5,
    players: [
      ["Viktor Gyökeres", "Delantero"],
      ["Alexander Isak", "Delantero"],
      ["Dejan Kulusevski", "Extremo"],
    ],
  },
  turkey: {
    id: "turkey",
    name: "Turquía",
    shortName: "TUR",
    flagCode: "tr",
    color: "#e30000",
    group: "D",
    bestParticipation: "Tercer lugar, 2002",
    probability: 0.45,
    players: [
      ["Hakan Çalhanoğlu", "Mediocampista"],
      ["Arda Güler", "Mediapunta"],
      ["Kenan Yıldız", "Delantero"],
    ],
  },
  "czech-republic": {
    id: "czech-republic",
    name: "República Checa",
    shortName: "CZE",
    flagCode: "cz",
    color: "#3150f4",
    group: "A",
    bestParticipation: "Subcampeón, 1934 y 1962 como Checoslovaquia",
    probability: 0.14,
    players: [
      ["Patrik Schick", "Delantero"],
      ["Tomáš Souček", "Mediocampista"],
      ["Adam Hložek", "Delantero"],
    ],
  },
  "dr-congo": {
    id: "dr-congo",
    name: "RD Congo",
    shortName: "COD",
    flagCode: "cd",
    color: "#3150f4",
    group: "K",
    bestParticipation: "Fase de grupos, 1974 como Zaire",
    probability: 0.03,
    players: [
      ["Yoane Wissa", "Delantero"],
      ["Chancel Mbemba", "Defensa central"],
      ["Cédric Bakambu", "Delantero"],
    ],
  },
  iraq: {
    id: "iraq",
    name: "Irak",
    shortName: "IRQ",
    flagCode: "iq",
    color: "#e30000",
    group: "I",
    bestParticipation: "Fase de grupos, 1986",
    probability: 0.03,
    players: [
      ["Aymen Hussein", "Delantero"],
      ["Ali Jasim", "Extremo"],
      ["Zidane Iqbal", "Mediocampista"],
    ],
  },
};
