const FIFA_COLORS = [
  "#e30000",
  "#6c00f4",
  "#3150f4",
  "#005845",
  "#ff3d12",
  "#a47cf4",
  "#06ca4f",
  "#a4ed00",
  "#ff9a82",
  "#e81768",
  "#59edcc",
  "#eaff2f",
];

const DATA_SOURCES = {
  groups: {
    label: "Grupos",
    name: "FIFA World Cup 2026 / Opta Analyst",
    url: "https://theanalyst.com/articles/fifa-world-cup-2026-groups-predictions-previews",
  },
  probability: {
    label: "Probabilidad",
    name: "Opta Analyst Supercomputer, junio 2026",
    url: "https://theanalyst.com/articles/who-will-win-2026-fifa-world-cup-predictions-opta-supercomputer",
  },
  history: {
    label: "Historial",
    name: "Historial mundialista FIFA/Wikipedia",
    url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/teams",
  },
};

const GROUPS = {
  A: ["mexico", "south-africa", "korea", "czech-republic"],
  B: ["canada", "bosnia", "qatar", "switzerland"],
  C: ["brazil", "morocco", "haiti", "scotland"],
  D: ["usa", "paraguay", "australia", "turkey"],
  E: ["germany", "curacao", "cote-divoire", "ecuador"],
  F: ["netherlands", "japan", "sweden", "tunisia"],
  G: ["belgium", "egypt", "iran", "new-zealand"],
  H: ["spain", "cabo-verde", "saudi-arabia", "uruguay"],
  I: ["france", "senegal", "iraq", "norway"],
  J: ["argentina", "algeria", "austria", "jordan"],
  K: ["portugal", "dr-congo", "uzbekistan", "colombia"],
  L: ["england", "croatia", "ghana", "panama"],
};

const POTS = [
  {
    id: 1,
    name: "Bombo 1",
    countries: [
      "canada",
      "mexico",
      "usa",
      "spain",
      "argentina",
      "france",
      "england",
      "brazil",
      "portugal",
      "netherlands",
      "belgium",
      "germany",
    ],
  },
  {
    id: 2,
    name: "Bombo 2",
    countries: [
      "croatia",
      "morocco",
      "colombia",
      "uruguay",
      "switzerland",
      "japan",
      "senegal",
      "iran",
      "korea",
      "ecuador",
      "austria",
      "australia",
    ],
  },
  {
    id: 3,
    name: "Bombo 3",
    countries: [
      "norway",
      "panama",
      "egypt",
      "algeria",
      "scotland",
      "paraguay",
      "tunisia",
      "cote-divoire",
      "uzbekistan",
      "qatar",
      "saudi-arabia",
      "south-africa",
    ],
  },
  {
    id: 4,
    name: "Bombo 4",
    countries: [
      "jordan",
      "cabo-verde",
      "ghana",
      "curacao",
      "haiti",
      "new-zealand",
      "bosnia",
      "sweden",
      "turkey",
      "czech-republic",
      "dr-congo",
      "iraq",
    ],
  },
];

const COUNTRY_DATA = {
  canada: {
    id: "canada",
    name: "Canadá",
    shortName: "CAN",
    flagCode: "ca",
    color: "#e30000",
    group: "B",
    bestParticipation: "Fase de grupos",
    probability: 0.12,
    players: [
      ["Alphonso Davies", "Lateral izquierdo", "assets/players/canada-alphonso-davies.jpg"],
      ["Jonathan David", "Delantero", "assets/players/canada-jonathan-david.jpg"],
      ["Stephen Eustáquio", "Mediocampista", "assets/players/canada-stephen-eustaquio.jpg"],
    ],
  },
  mexico: {
    id: "mexico",
    name: "México",
    shortName: "MEX",
    flagCode: "mx",
    color: "#005845",
    group: "A",
    bestParticipation: "Cuartos de final, 1970 y 1986",
    probability: 0.8,
    players: [
      ["Edson Álvarez", "Mediocentro", "assets/players/mexico-edson-alvarez.png"],
      ["Santiago Giménez", "Delantero", "assets/players/mexico-santiago-gimenez.png"],
      ["Johan Vásquez", "Defensa central", "assets/players/mexico-johan-vasquez.jpg"],
    ],
  },
  usa: {
    id: "usa",
    name: "Estados Unidos",
    shortName: "USA",
    flagCode: "us",
    color: "#3150f4",
    group: "D",
    bestParticipation: "Tercer lugar, 1930",
    probability: 1.2,
    players: [
      ["Christian Pulisic", "Extremo", "assets/players/usa-christian-pulisic.jpg"],
      ["Weston McKennie", "Mediocampista", "assets/players/usa-weston-mckennie.jpg"],
      ["Tyler Adams", "Mediocentro", "assets/players/usa-tyler-adams.jpg"],
    ],
  },
  spain: {
    id: "spain",
    name: "España",
    shortName: "ESP",
    flagCode: "es",
    color: "#e30000",
    group: "H",
    bestParticipation: "Campeón, 2010",
    probability: 16.1,
    players: [
      ["Lamine Yamal", "Extremo", "assets/players/spain-lamine-yamal.jpg"],
      ["Rodri", "Mediocentro", "assets/players/spain-rodri.jpg"],
      ["Pedri", "Mediocampista", "assets/players/spain-pedri.jpg"],
    ],
  },
  argentina: {
    id: "argentina",
    name: "Argentina",
    shortName: "ARG",
    flagCode: "ar",
    color: "#59aee8",
    group: "J",
    bestParticipation: "Campeón, 1978, 1986 y 2022",
    probability: 10.4,
    players: [
      ["Lionel Messi", "Delantero", "assets/players/argentina-lionel-messi.jpg"],
      ["Lautaro Martínez", "Delantero", "assets/players/argentina-lautaro-martinez.jpg"],
      ["Emiliano Martínez", "Portero", "assets/players/argentina-emiliano-martinez.jpg"],
    ],
  },
  france: {
    id: "france",
    name: "Francia",
    shortName: "FRA",
    flagCode: "fr",
    color: "#3150f4",
    group: "I",
    bestParticipation: "Campeón, 1998 y 2018",
    probability: 13,
    players: [
      ["Kylian Mbappé", "Delantero", "assets/players/france-kylian-mbappe.jpg"],
      ["Ousmane Dembélé", "Extremo", "assets/players/france-ousmane-dembele.jpg"],
      ["Michael Olise", "Extremo", "assets/players/france-michael-olise.jpg"],
    ],
  },
  england: {
    id: "england",
    name: "Inglaterra",
    shortName: "ENG",
    flagCode: "gb-eng",
    color: "#ffffff",
    group: "L",
    bestParticipation: "Campeón, 1966",
    probability: 11.2,
    players: [
      ["Harry Kane", "Delantero", "assets/players/england-harry-kane.jpg"],
      ["Jude Bellingham", "Mediocampista", "assets/players/england-jude-bellingham.jpg"],
      ["Bukayo Saka", "Extremo", "assets/players/england-bukayo-saka.jpg"],
    ],
  },
  brazil: {
    id: "brazil",
    name: "Brasil",
    shortName: "BRA",
    flagCode: "br",
    color: "#06ca4f",
    group: "C",
    bestParticipation: "Campeón, 1958, 1962, 1970, 1994 y 2002",
    probability: 6.6,
    players: [
      ["Neymar", "Extremo", "assets/players/brazil-neymar.jpg"],
      ["Vinícius Júnior", "Extremo", "assets/players/brazil-vinicius-junior.jpg"],
      ["Marquinhos", "Defensa central", "assets/players/brazil-marquinhos.jpg"],
    ],
  },
  portugal: {
    id: "portugal",
    name: "Portugal",
    shortName: "POR",
    flagCode: "pt",
    color: "#e30000",
    group: "K",
    bestParticipation: "Tercer lugar, 1966",
    probability: 7,
    players: [
      ["Cristiano Ronaldo", "Delantero", "assets/players/portugal-cristiano-ronaldo.jpg"],
      ["Bruno Fernandes", "Mediocampista", "assets/players/portugal-bruno-fernandes.jpg"],
      ["Vitinha", "Mediocampista", "assets/players/portugal-vitinha.jpg"],
    ],
  },
  netherlands: {
    id: "netherlands",
    name: "Países Bajos",
    shortName: "NED",
    flagCode: "nl",
    color: "#ff6f00",
    group: "F",
    bestParticipation: "Subcampeón, 1974, 1978 y 2010",
    probability: 3.6,
    players: [
      ["Virgil van Dijk", "Defensa central", "assets/players/netherlands-virgil-van-dijk.jpg"],
      ["Frenkie de Jong", "Mediocampista", "assets/players/netherlands-frenkie-de-jong.jpg"],
      ["Cody Gakpo", "Extremo", "assets/players/netherlands-cody-gakpo.jpg"],
    ],
  },
  belgium: {
    id: "belgium",
    name: "Bélgica",
    shortName: "BEL",
    flagCode: "be",
    color: "#e30000",
    group: "G",
    bestParticipation: "Tercer lugar, 2018",
    probability: 2.4,
    players: [
      ["Kevin De Bruyne", "Mediocampista", "assets/players/belgium-kevin-de-bruyne.jpg"],
      ["Jérémy Doku", "Extremo", "assets/players/belgium-jeremy-doku.jpg"],
      ["Thibaut Courtois", "Portero", "assets/players/belgium-thibaut-courtois.jpg"],
    ],
  },
  germany: {
    id: "germany",
    name: "Alemania",
    shortName: "GER",
    flagCode: "de",
    color: "#111111",
    group: "E",
    bestParticipation: "Campeón, 1954, 1974, 1990 y 2014",
    probability: 5.1,
    players: [
      ["Jamal Musiala", "Mediapunta", "assets/players/germany-jamal-musiala.jpg"],
      ["Florian Wirtz", "Mediapunta", "assets/players/germany-florian-wirtz.jpg"],
      ["Joshua Kimmich", "Mediocampista", "assets/players/germany-joshua-kimmich.jpg"],
    ],
  },
  croatia: {
    id: "croatia",
    name: "Croacia",
    shortName: "CRO",
    flagCode: "hr",
    color: "#ffffff",
    group: "L",
    bestParticipation: "Subcampeón, 2018",
    probability: 1.6,
    players: [
      ["Luka Modrić", "Mediocampista", "assets/players/croatia-luka-modric.jpg"],
      ["Joško Gvardiol", "Defensa", "assets/players/croatia-josko-gvardiol.jpg"],
      ["Mateo Kovačić", "Mediocampista", "assets/players/croatia-mateo-kovacic.jpg"],
    ],
  },
  morocco: {
    id: "morocco",
    name: "Marruecos",
    shortName: "MAR",
    flagCode: "ma",
    color: "#e30000",
    group: "C",
    bestParticipation: "Semifinales, 2022",
    probability: 1.9,
    players: [
      ["Achraf Hakimi", "Lateral derecho", "assets/players/morocco-achraf-hakimi.jpg"],
      ["Yassine Bounou", "Portero", "assets/players/morocco-yassine-bounou.jpg"],
      ["Sofyan Amrabat", "Mediocentro", "assets/players/morocco-sofyan-amrabat.jpg"],
    ],
  },
  colombia: {
    id: "colombia",
    name: "Colombia",
    shortName: "COL",
    flagCode: "co",
    color: "#f7d117",
    group: "K",
    bestParticipation: "Cuartos de final, 2014",
    probability: 2.1,
    players: [
      ["Luis Díaz", "Extremo", "assets/players/colombia-luis-diaz.jpg"],
      ["James Rodríguez", "Mediapunta", "assets/players/colombia-james-rodriguez.jpg"],
      ["Daniel Muñoz", "Defensa", "assets/players/colombia-daniel-munoz.jpg"],
    ],
  },
  uruguay: {
    id: "uruguay",
    name: "Uruguay",
    shortName: "URU",
    flagCode: "uy",
    color: "#59aee8",
    group: "H",
    bestParticipation: "Campeón, 1930 y 1950",
    probability: 1.1,
    players: [
      ["Federico Valverde", "Mediocampista", "assets/players/uruguay-federico-valverde.jpg"],
      ["Darwin Núñez", "Delantero", "assets/players/uruguay-darwin-nunez.jpg"],
      ["Ronald Araújo", "Defensa central", "assets/players/uruguay-ronald-araujo.jpg"],
    ],
  },
  switzerland: {
    id: "switzerland",
    name: "Suiza",
    shortName: "SUI",
    flagCode: "ch",
    color: "#e30000",
    group: "B",
    bestParticipation: "Cuartos de final, 1934, 1938 y 1954",
    probability: 1,
    players: [
      ["Granit Xhaka", "Mediocampista", "assets/players/switzerland-granit-xhaka.jpg"],
      ["Manuel Akanji", "Defensa central", "assets/players/switzerland-manuel-akanji.jpg"],
      ["Gregor Kobel", "Portero", "assets/players/switzerland-gregor-kobel.jpg"],
    ],
  },
  japan: {
    id: "japan",
    name: "Japón",
    shortName: "JPN",
    flagCode: "jp",
    color: "#1260f0",
    group: "F",
    bestParticipation: "Octavos de final",
    probability: 0.9,
    players: [
      ["Kaoru Mitoma", "Extremo", "assets/players/japan-kaoru-mitoma.png"],
      ["Takefusa Kubo", "Mediapunta", "assets/players/japan-takefusa-kubo.jpg"],
      ["Wataru Endo", "Mediocentro", "assets/players/japan-wataru-endo.jpg"],
    ],
  },
  senegal: {
    id: "senegal",
    name: "Senegal",
    shortName: "SEN",
    flagCode: "sn",
    color: "#0d8d3c",
    group: "I",
    bestParticipation: "Cuartos de final, 2002",
    probability: 0.7,
    players: [
      ["Sadio Mané", "Delantero", "assets/players/senegal-sadio-mane.jpg"],
      ["Kalidou Koulibaly", "Defensa central", "assets/players/senegal-kalidou-koulibaly.jpg"],
      ["Pape Matar Sarr", "Mediocampista", "assets/players/senegal-pape-matar-sarr.jpg"],
    ],
  },
  iran: {
    id: "iran",
    name: "Irán",
    shortName: "IRN",
    flagCode: "ir",
    color: "#ffffff",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.16,
    players: [
      ["Mehdi Taremi", "Delantero", "assets/players/iran-mehdi-taremi.jpg"],
      ["Saman Ghoddos", "Mediocampista", "assets/players/iran-saman-ghoddos.jpg"],
      ["Alireza Jahanbakhsh", "Extremo", "assets/players/iran-alireza-jahanbakhsh.jpg"],
    ],
  },
  korea: {
    id: "korea",
    name: "Corea del Sur",
    shortName: "KOR",
    flagCode: "kr",
    color: "#f04e31",
    group: "A",
    bestParticipation: "Cuarto lugar, 2002",
    probability: 0.22,
    players: [
      ["Son Heung-min", "Delantero", "assets/players/korea-son-heung-min.jpg"],
      ["Kim Min-jae", "Defensa central", "assets/players/korea-kim-min-jae.jpg"],
      ["Lee Kang-in", "Mediapunta", "assets/players/korea-lee-kang-in.jpg"],
    ],
  },
  ecuador: {
    id: "ecuador",
    name: "Ecuador",
    shortName: "ECU",
    flagCode: "ec",
    color: "#f7d117",
    group: "E",
    bestParticipation: "Octavos de final, 2006",
    probability: 1.4,
    players: [
      ["Moisés Caicedo", "Mediocampista", "assets/players/ecuador-moises-caicedo.jpg"],
      ["Piero Hincapié", "Defensa central", "assets/players/ecuador-piero-hincapie.jpg"],
      ["Pervis Estupiñán", "Lateral izquierdo", "assets/players/ecuador-pervis-estupinan.jpg"],
    ],
  },
  austria: {
    id: "austria",
    name: "Austria",
    shortName: "AUT",
    flagCode: "at",
    color: "#e30000",
    group: "J",
    bestParticipation: "Tercer lugar, 1954",
    probability: 0.6,
    players: [
      ["David Alaba", "Defensa", "assets/players/austria-david-alaba.jpg"],
      ["Marcel Sabitzer", "Mediocampista", "assets/players/austria-marcel-sabitzer.jpg"],
      ["Konrad Laimer", "Mediocampista", "assets/players/austria-konrad-laimer.jpg"],
    ],
  },
  australia: {
    id: "australia",
    name: "Australia",
    shortName: "AUS",
    flagCode: "au",
    color: "#f7d117",
    group: "D",
    bestParticipation: "Octavos de final, 2006 y 2022",
    probability: 0.28,
    players: [
      ["Mathew Ryan", "Portero", "assets/players/australia-mathew-ryan.jpg"],
      ["Jackson Irvine", "Mediocampista", "assets/players/australia-jackson-irvine.jpg"],
      ["Harry Souttar", "Defensa central", "assets/players/australia-harry-souttar.jpg"],
    ],
  },
  norway: {
    id: "norway",
    name: "Noruega",
    shortName: "NOR",
    flagCode: "no",
    color: "#e30000",
    group: "I",
    bestParticipation: "Octavos de final, 1998",
    probability: 3.5,
    players: [
      ["Erling Haaland", "Delantero", "assets/players/norway-erling-haaland.jpg"],
      ["Martin Ødegaard", "Mediocampista", "assets/players/norway-martin-odegaard.jpg"],
      ["Alexander Sørloth", "Delantero", "assets/players/norway-alexander-sorloth.jpg"],
    ],
  },
  panama: {
    id: "panama",
    name: "Panamá",
    shortName: "PAN",
    flagCode: "pa",
    color: "#ffffff",
    group: "L",
    bestParticipation: "Fase de grupos, 2018",
    probability: 0.07,
    players: [
      ["Michael Murillo", "Lateral derecho", "assets/players/panama-michael-murillo.jpg"],
      ["Adalberto Carrasquilla", "Mediocampista", "assets/players/panama-adalberto-carrasquilla.jpg"],
      ["José Fajardo", "Delantero"],
    ],
  },
  egypt: {
    id: "egypt",
    name: "Egipto",
    shortName: "EGY",
    flagCode: "eg",
    color: "#ffffff",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.18,
    players: [
      ["Mohamed Salah", "Extremo", "assets/players/egypt-mohamed-salah.jpg"],
      ["Omar Marmoush", "Delantero", "assets/players/egypt-omar-marmoush.png"],
      ["Trézéguet", "Extremo", "assets/players/egypt-trezeguet.jpg"],
    ],
  },
  algeria: {
    id: "algeria",
    name: "Argelia",
    shortName: "ALG",
    flagCode: "dz",
    color: "#06ca4f",
    group: "J",
    bestParticipation: "Octavos de final, 2014",
    probability: 0.2,
    players: [
      ["Riyad Mahrez", "Extremo", "assets/players/algeria-riyad-mahrez.jpg"],
      ["Ismaël Bennacer", "Mediocampista", "assets/players/algeria-ismael-bennacer.jpg"],
      ["Ramy Bensebaini", "Defensa", "assets/players/algeria-ramy-bensebaini.jpg"],
    ],
  },
  scotland: {
    id: "scotland",
    name: "Escocia",
    shortName: "SCO",
    flagCode: "gb-sct",
    color: "#3150f4",
    group: "C",
    bestParticipation: "Fase de grupos",
    probability: 0.2,
    players: [
      ["Andy Robertson", "Lateral izquierdo", "assets/players/scotland-andy-robertson.jpg"],
      ["Scott McTominay", "Mediocampista", "assets/players/scotland-scott-mctominay.jpg"],
      ["John McGinn", "Mediocampista", "assets/players/scotland-john-mcginn.jpg"],
    ],
  },
  paraguay: {
    id: "paraguay",
    name: "Paraguay",
    shortName: "PAR",
    flagCode: "py",
    color: "#e30000",
    group: "D",
    bestParticipation: "Cuartos de final, 2010",
    probability: 0.35,
    players: [
      ["Miguel Almirón", "Mediapunta", "assets/players/paraguay-miguel-almiron.jpg"],
      ["Julio Enciso", "Delantero", "assets/players/paraguay-julio-enciso.jpg"],
      ["Diego Gómez", "Mediocampista", "assets/players/paraguay-diego-gomez.jpg"],
    ],
  },
  tunisia: {
    id: "tunisia",
    name: "Túnez",
    shortName: "TUN",
    flagCode: "tn",
    color: "#ffffff",
    group: "F",
    bestParticipation: "Fase de grupos",
    probability: 0.09,
    players: [
      ["Ellyes Skhiri", "Mediocampista", "assets/players/tunisia-ellyes-skhiri.jpg"],
      ["Hannibal Mejbri", "Mediocampista", "assets/players/tunisia-hannibal-mejbri.jpg"],
      ["Ali Abdi", "Lateral izquierdo", "assets/players/tunisia-ali-abdi.png"],
    ],
  },
  "cote-divoire": {
    id: "cote-divoire",
    name: "Costa de Marfil",
    shortName: "CIV",
    flagCode: "ci",
    color: "#ff7a00",
    group: "E",
    bestParticipation: "Fase de grupos",
    probability: 0.4,
    players: [
      ["Franck Kessié", "Mediocampista", "assets/players/cote-divoire-franck-kessie.jpg"],
      ["Amad Diallo", "Extremo", "assets/players/cote-divoire-amad-diallo.jpg"],
      ["Evan Ndicka", "Defensa central", "assets/players/cote-divoire-evan-ndicka.jpg"],
    ],
  },
  uzbekistan: {
    id: "uzbekistan",
    name: "Uzbekistán",
    shortName: "UZB",
    flagCode: "uz",
    color: "#59edcc",
    group: "K",
    bestParticipation: "Debut mundialista",
    probability: 0.04,
    players: [
      ["Eldor Shomurodov", "Delantero", "assets/players/uzbekistan-eldor-shomurodov.jpg"],
      ["Abbosbek Fayzullaev", "Mediapunta", "assets/players/uzbekistan-abbosbek-fayzullaev.png"],
      ["Abdukodir Khusanov", "Defensa central", "assets/players/uzbekistan-abdukodir-khusanov.jpg"],
    ],
  },
  qatar: {
    id: "qatar",
    name: "Catar",
    shortName: "QAT",
    flagCode: "qa",
    color: "#850d0d",
    group: "B",
    bestParticipation: "Fase de grupos, 2022",
    probability: 0.08,
    players: [
      ["Akram Afif", "Extremo", "assets/players/qatar-akram-afif.jpg"],
      ["Almoez Ali", "Delantero", "assets/players/qatar-almoez-ali.jpg"],
      ["Boualem Khoukhi", "Defensa", "assets/players/qatar-boualem-khoukhi.png"],
    ],
  },
  "saudi-arabia": {
    id: "saudi-arabia",
    name: "Arabia Saudita",
    shortName: "KSA",
    flagCode: "sa",
    color: "#005845",
    group: "H",
    bestParticipation: "Octavos de final, 1994",
    probability: 0.11,
    players: [
      ["Salem Al-Dawsari", "Extremo", "assets/players/saudi-arabia-salem-al-dawsari.jpg"],
      ["Saud Abdulhamid", "Lateral derecho", "assets/players/saudi-arabia-saud-abdulhamid.jpg"],
      ["Firas Al-Buraikan", "Delantero", "assets/players/saudi-arabia-firas-al-buraikan.jpg"],
    ],
  },
  "south-africa": {
    id: "south-africa",
    name: "Sudáfrica",
    shortName: "RSA",
    flagCode: "za",
    color: "#e4c933",
    group: "A",
    bestParticipation: "Fase de grupos",
    probability: 0.1,
    players: [
      ["Ronwen Williams", "Portero", "assets/players/south-africa-ronwen-williams.jpg"],
      ["Teboho Mokoena", "Mediocampista"],
      ["Percy Tau", "Delantero", "assets/players/south-africa-percy-tau.jpg"],
    ],
  },
  jordan: {
    id: "jordan",
    name: "Jordania",
    shortName: "JOR",
    flagCode: "jo",
    color: "#e30000",
    group: "J",
    bestParticipation: "Debut mundialista",
    probability: 0.02,
    players: [
      ["Musa Al-Taamari", "Extremo", "assets/players/jordan-musa-al-taamari.png"],
      ["Yazan Al-Naimat", "Delantero", "assets/players/jordan-yazan-al-naimat.jpg"],
      ["Noor Al-Rawabdeh", "Mediocampista", "assets/players/jordan-noor-al-rawabdeh.png"],
    ],
  },
  "cabo-verde": {
    id: "cabo-verde",
    name: "Cabo Verde",
    shortName: "CPV",
    flagCode: "cv",
    color: "#3150f4",
    group: "H",
    bestParticipation: "Debut mundialista",
    probability: 0.02,
    players: [
      ["Ryan Mendes", "Extremo", "assets/players/cabo-verde-ryan-mendes.jpg"],
      ["Garry Rodrigues", "Extremo", "assets/players/cabo-verde-garry-rodrigues.jpg"],
      ["Logan Costa", "Defensa central", "assets/players/cabo-verde-logan-costa.jpg"],
    ],
  },
  ghana: {
    id: "ghana",
    name: "Ghana",
    shortName: "GHA",
    flagCode: "gh",
    color: "#f7d117",
    group: "L",
    bestParticipation: "Cuartos de final, 2010",
    probability: 0.25,
    players: [
      ["Mohammed Kudus", "Mediapunta", "assets/players/ghana-mohammed-kudus.jpg"],
      ["Thomas Partey", "Mediocampista", "assets/players/ghana-thomas-partey.jpg"],
      ["Antoine Semenyo", "Delantero", "assets/players/ghana-antoine-semenyo.png"],
    ],
  },
  curacao: {
    id: "curacao",
    name: "Curazao",
    shortName: "CUW",
    flagCode: "cw",
    color: "#3150f4",
    group: "E",
    bestParticipation: "Debut mundialista",
    probability: 0.005,
    players: [
      ["Juninho Bacuna", "Mediocampista", "assets/players/curacao-juninho-bacuna.jpg"],
      ["Eloy Room", "Portero", "assets/players/curacao-eloy-room.jpg"],
      ["Juriën Gaari", "Defensa", "assets/players/curacao-jurien-gaari.jpg"],
    ],
  },
  haiti: {
    id: "haiti",
    name: "Haití",
    shortName: "HAI",
    flagCode: "ht",
    color: "#ffffff",
    group: "C",
    bestParticipation: "Fase de grupos, 1974",
    probability: 0.01,
    players: [
      ["Duckens Nazon", "Delantero", "assets/players/haiti-duckens-nazon.jpg"],
      ["Frantzdy Pierrot", "Delantero"],
      ["Jean-Ricner Bellegarde", "Mediocampista", "assets/players/haiti-jean-ricner-bellegarde.jpg"],
    ],
  },
  "new-zealand": {
    id: "new-zealand",
    name: "Nueva Zelanda",
    shortName: "NZL",
    flagCode: "nz",
    color: "#111111",
    group: "G",
    bestParticipation: "Fase de grupos",
    probability: 0.05,
    players: [
      ["Chris Wood", "Delantero", "assets/players/new-zealand-chris-wood.jpg"],
      ["Sarpreet Singh", "Mediocampista", "assets/players/new-zealand-sarpreet-singh.png"],
      ["Tim Payne", "Mediocampista", "assets/players/new-zealand-tim-payne.jpg"],
    ],
  },
  bosnia: {
    id: "bosnia",
    name: "Bosnia y Herzegovina",
    shortName: "BIH",
    flagCode: "ba",
    color: "#3150f4",
    group: "B",
    bestParticipation: "Fase de grupos, 2014",
    probability: 0.06,
    players: [
      ["Edin Džeko", "Delantero", "assets/players/bosnia-edin-dzeko.jpg"],
      ["Sead Kolašinac", "Defensa", "assets/players/bosnia-sead-kolasinac.jpg"],
      ["Amar Dedić", "Lateral derecho", "assets/players/bosnia-amar-dedic.jpg"],
    ],
  },
  sweden: {
    id: "sweden",
    name: "Suecia",
    shortName: "SWE",
    flagCode: "se",
    color: "#f7d117",
    group: "F",
    bestParticipation: "Subcampeón, 1958",
    probability: 0.5,
    players: [
      ["Viktor Gyökeres", "Delantero", "assets/players/sweden-viktor-gyokeres.jpg"],
      ["Alexander Isak", "Delantero", "assets/players/sweden-alexander-isak.jpg"],
      ["Dejan Kulusevski", "Extremo", "assets/players/sweden-dejan-kulusevski.jpg"],
    ],
  },
  turkey: {
    id: "turkey",
    name: "Turquía",
    shortName: "TUR",
    flagCode: "tr",
    color: "#e30000",
    group: "D",
    bestParticipation: "Tercer lugar, 2002",
    probability: 0.45,
    players: [
      ["Hakan Çalhanoğlu", "Mediocampista", "assets/players/turkey-hakan-calhanoglu.jpg"],
      ["Arda Güler", "Mediapunta", "assets/players/turkey-arda-guler.jpg"],
      ["Kenan Yildiz", "Delantero", "assets/players/turkey-kenan-yildiz.jpg"],
    ],
  },
  "czech-republic": {
    id: "czech-republic",
    name: "República Checa",
    shortName: "CZE",
    flagCode: "cz",
    color: "#ee3832",
    group: "A",
    bestParticipation: "Subcampeón, 1934 y 1962 como Checoslovaquia",
    probability: 0.14,
    players: [
      ["Patrik Schick", "Delantero", "assets/players/czech-republic-patrik-schick.jpg"],
      ["Tomáš Souček", "Mediocampista", "assets/players/czech-republic-tomas-soucek.jpg"],
      ["Adam Hložek", "Delantero", "assets/players/czech-republic-adam-hlozek.jpg"],
    ],
  },
  "dr-congo": {
    id: "dr-congo",
    name: "RD Congo",
    shortName: "COD",
    flagCode: "cd",
    color: "#3150f4",
    group: "K",
    bestParticipation: "Fase de grupos, 1974 como Zaire",
    probability: 0.03,
    players: [
      ["Yoane Wissa", "Delantero", "assets/players/dr-congo-yoane-wissa.jpg"],
      ["Chancel Mbemba", "Defensa central", "assets/players/dr-congo-chancel-mbemba.jpg"],
      ["Cédric Bakambu", "Delantero", "assets/players/dr-congo-cedric-bakambu.jpg"],
    ],
  },
  iraq: {
    id: "iraq",
    name: "Irak",
    shortName: "IRQ",
    flagCode: "iq",
    color: "#ffffff",
    group: "I",
    bestParticipation: "Fase de grupos, 1986",
    probability: 0.03,
    players: [
      ["Aymen Hussein", "Delantero", "assets/players/iraq-aymen-hussein.jpg"],
      ["Ali Jasim", "Extremo"],
      ["Zidane Iqbal", "Mediocampista", "assets/players/iraq-zidane-iqbal.jpg"],
    ],
  },
};
